config/routes.rb
Tsh::Application.routes.draw do
  devise_for :users

  root 'pages#index'
  get '/settings' => 'pages#index'
  get '/docs' => 'pages#docs'
  get '/facebook' => 'facebook#index'
  get '/facebook/callback' => 'facebook#callback'
  get '/gmail' => 'gmail#index'
  get '/gmail/callback' => 'gmail#callback'

  resource :sms, only: :create
end

app/models/command.rb
class Command
  def self.run(command, options={})
    ["hi"]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :phone_number
  end
end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController
  def index
    session['oauth'] = Koala::Facebook::OAuth.new(ENV['FB_ID'], ENV['FB_SECRET'], "#{root_url}facebook/callback")
    redirect_to session['oauth'].url_for_oauth_code(scope: 'manage_notifications,publish_actions')
  end

  def callback
    current_user.update(fb_access_token: session['oauth'].get_access_token(params[:code]))
    redirect_to root_path
  end
end

app/controllers/gmail_controller.rb
class GmailController < ApplicationController
  def index
    client = OAuth2::Client.new(ENV['GM_ID'], ENV['GM_SECRET'],
      site: 'https://accounts.google.com',
      authorize_url: '/o/oauth2/auth',
      token_url: '/o/oauth2/token'
    )
    redirect_to client.auth_code.authorize_url(redirect_uri: "#{root_url}gmail/callback", scope: 'https://mail.google.com/ https://www.googleapis.com/auth/userinfo.email')
  end

  def callback
    client = OAuth2::Client.new(ENV['GM_ID'], ENV['GM_SECRET'],
      site: 'https://accounts.google.com',
      authorize_url: '/o/oauth2/auth',
      token_url: '/o/oauth2/token'
    )
    access_token = client.auth_code.get_token(params[:code], redirect_uri: "#{root_url}gmail/callback")
    email = access_token.get('https://www.googleapis.com/userinfo/email?alt=json').parsed
    current_user.update(gm_access_token: access_token.token, gm_email: email['data']['email'])

    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/sms_controller.rb
class SmsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def create
    response = Twilio::TwiML::Response.new do |r|
      # responses = Command.run(params[:Body], from: params[:From])

      responses = ["hi", "hi", "hi"]

      responses.each do |res|
        r.Sms res
      end
    end

    render xml: response.text
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Text Shell</title>

  <%= stylesheet_link_tag '//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to root_path do %>
    <%= image_tag 'logo.png', width: 100 %>
  <% end %>

  <div class='row'>
    <div class='col-md-3'></div>
    <div class='col-md-6 container'>
      <hr>
      <%= yield %>
      <hr>
    </div>
  </div>

  <div class='btn-group'>
    <%= link_to docs_path, class: 'btn btn-default' do %>
      <i class='fa fa-files-o fa-2x'></i> Docs
    <% end %>

    <% if user_signed_in? %>
      <%= link_to '/settings', class: 'btn btn-default' do %>
        <i class='fa fa-cogs fa-2x'></i> Settings
      <% end %>

      <%= link_to destroy_user_session_path, class: 'btn btn-default', method: :delete do %>
        <i class='fa fa-sign-out fa-2x'></i> Sign Out
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: 'btn btn-default' do %>
        <i class='fa fa-sign-in fa-2x'></i> Sign In
      <% end %>
    <% end %>
  </div>
</body>
</html>

app/views/pages/_home.html.erb
<div class='row'>
  <div class='col-md-6 text-right'>
    <%= image_tag 'phone2.png', height: 400 %>
  </div>

  <div class='col-md-5'>
    <p class='lead'>
      Get your Facebook notifications and unread emails without data or wifi, but via text.
    </p>

    <hr>

    <ul>
      <li>Notifications, messages via Facebook</li>
      <li>Unread email via Gmail</li>
      <li>Weather via Wunderground</li>
      <li>Translations via Bing</li>
    </ul>

    <hr>

    <p>Designed and developed for the CreateHS challenge.</p>

    <div class='text-center'>
      <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary' %>
      <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/pages/_settings.html.erb
<p class='lead'>
  You may now text <strong>(646) 863-7942</strong> with any commands found on the <%= link_to 'docs', docs_path %>.
</p>

<%= link_to 'Enable Facebook', facebook_path, class: 'btn btn-primary btn-lg btn-block' %>
<%= link_to 'Enable Gmail', gmail_path, class: 'btn btn-danger btn-lg btn-block' %>

app/views/pages/docs.html.erb
<table class='table table-bordered table-striped table-hover docs'>
  <thead>
    <tr>
      <th>Command</th>
      <th>Response</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td class='gray_hue'>calc 2 + 2
      <td>4</td>
    </tr>

    <tr>
      <td class='gray_hue'>weather San Jose, CA</td>
      <td>Today, the temperature is 66</td>
    </tr>

    <tr>
      <td class='blue_hue'>fb post Having fun at HSHacks!</td>
      <td>Posted successfully.</td>
    </tr>

    <tr>
      <td class='blue_hue'>fb list notifs</td>
      <td>Rishi Dhanaraj added a photo of you.</td>
    </tr>

    <tr>
      <td class='red_hue'>gmail list</td>
      <td>TSH: Account Verification</td>
    </tr>

    <tr>
      <td class='gray_hue'>translate en Bonjour</td>
      <td>Hello</td>
    </tr>
  </tbody>
</table>

app/views/pages/home.html.erb
<p class='lead'>
  You may now text <strong>(646) 863-7942</strong> with any commands found on the <%= link_to 'docs', docs_path %>.
</p>

<%= link_to facebook_path, class: 'btn btn-primary btn-lg btn-block' do %>
  Enable Facebook
<% end %>
<%= link_to 'Enable Gmail', gmail_path, class: 'btn btn-danger btn-lg btn-block' %>

app/views/pages/index.html.erb
<% if user_signed_in? %>
  <%= render 'settings' %>
<% else %>
  <%= render 'home' %>
<% end %>